---
- name: "SCORED | 1.1.1 | PATCH | L1 | MASTER | Ensure that the API server pod specification file permissions are set to 600 or more restrictive"
  file:
    path: "{{ api_server_pod_specification_file }}"
    state: file
    mode: 0600
  when:
    - rule_1_1_1
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.1
    - master

- name: "SCORED | 1.1.2 | PATCH | L1 | MASTER | Ensure that the API server pod specification file ownership is set to root:root"
  file:
    path: "{{ api_server_pod_specification_file }}"
    state: file
    owner: root
    group: root
  when:
    - rule_1_1_2
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.2
    - master

- name: "SCORED | 1.1.3 | PATCH | L1 | MASTER | Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive"
  file:
    path: "{{ controller_manager_pod_specification_file }}"
    state: file
    mode: 0600
  when:
    - rule_1_1_3
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.3
    - master

- name: "SCORED | 1.1.4 | PATCH | L1 | MASTER | Ensure that the controller manager pod specification file ownership is set to root:root"
  file:
    path: "{{ controller_manager_pod_specification_file }}"
    state: file
    owner: root
    group: root
  when:
    - rule_1_1_4
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.4
    - master

- name: "SCORED | 1.1.5 | PATCH | L1 | MASTER | Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive"
  file:
    path: "{{ scheduler_pod_specification_file }}"
    state: file
    mode: 0600
  when:
    - rule_1_1_5
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.5
    - master

- name: "SCORED | 1.1.6 | PATCH | L1 | MASTER | Ensure that the scheduler pod specification file ownership is set to root:root"
  file:
    path: "{{ scheduler_pod_specification_file }}"
    state: file
    owner: root
    group: root
  when:
    - rule_1_1_6
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.6
    - master

- name: "SCORED | 1.1.7 | PATCH | L1 | MASTER | Ensure that the etcd pod specification file permissions are set to 600 or more restrictive"
  file:
    path: "{{ etcd_pod_specification_file }}"
    state: file
    mode: 0600
  when:
    - rule_1_1_7
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.7
    - master

- name: "SCORED | 1.1.8 | PATCH | L1 | MASTER | Ensure that the etcd pod specification file ownership is set to root:root"
  file:
    path: "{{ etcd_pod_specification_file }}"
    state: file
    owner: root
    group: root
  when:
    - rule_1_1_8
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.8
    - master

- name: "SCORED | 1.1.9 | PATCH | L1 | MASTER | Ensure that the Container Network Interface file permissions are set to 600 or more restrictive"
  block:
    - name: "1.1.9 | Find Container Network Interface files"
      find:
        paths: /etc/cni/net.d
        patterns: "*.conf"
      register: cni_files
#    - name: DEBUG CNI file paths
#      debug:
#        msg: "{{ item.path }}"
#      loop: "{{ cni_files.files }}"
    - name: "SCORED | 1.1.9 | PATCH | L1 | MASTER | Ensure that the Container Network Interface file permissions are set to 600 or more restrictive"
      file:
        path: "{{ item.path }}"
        state: file
        mode: 0600
      loop: "{{ cni_files.files }}"
  when:
    - rule_1_1_9
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.9
    - master

- name: "SCORED | 1.1.10 | PATCH | L1 | MASTER | Ensure that the Container Network Interface file ownership is set to root:root"
  block:
    - name: "1.1.10 | Find Container Network Interface files"
      find:
        paths: /etc/cni/net.d
        patterns: "*.conf"
      register: cni_files
    - name: "SCORED | 1.1.10 | PATCH | L1 | MASTER | Ensure that the Container Network Interface file ownership is set to root:root"
      file:
        path: "{{ item.path }}"
        state: file
        owner: root
        group: root
      loop: "{{ cni_files.files }}"
  when:
    - rule_1_1_10
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.10
    - master


# On the etcd server node, get the etcd data directory, passed as an argument `--data-dir`, from the below command:
  # ps -ef | grep etcd
- name: "SCORED | 1.1.11 | PATCH | L1 | MASTER | Ensure that the etcd data directory permissions are set to 700 or more restrictive"
  file:
    path: "{{ etcd_data_directory }}"
    state: directory
    mode: 0700
  when:
    - rule_1_1_11
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.11
    - master
    - etcd
    - followup

# etcd user and group needs to be setup
- name: "SCORED | 1.1.12 | PATCH | L1 | MASTER | Ensure that the etcd data directory ownership is set to etcd:etcd"
  file:
    path: "{{ etcd_data_directory }}"
    state: directory
    owner: etcd
    group: etcd
  when:
    - rule_1_1_12
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.12
    - master
    - etcd
    - followup

- name: "SCORED | 1.1.13 | PATCH | L1 | MASTER | Ensure that the admin.conf file permissions are set to 600 or more restrictive"
  file:
    path: /etc/kubernetes/admin.conf
    state: file
    mode: 0600
  when:
    - rule_1_1_13
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.13
    - master

- name: "SCORED | 1.1.14 | PATCH | L1 | MASTER | Ensure that the admin.conf file ownership is set to root:root"
  file:
    path: /etc/kubernetes/admin.conf
    state: file
    owner: root
    group: root
  when:
    - rule_1_1_14
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.14
    - master

- name: "SCORED | 1.1.15 | PATCH | L1 | MASTER | Ensure that the scheduler.conf file permissions are set to 600 or more restrictive"
  file:
    path: /etc/kubernetes/scheduler.conf
    state: file
    mode: 0600
  when:
    - rule_1_1_15
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.15
    - master

- name: "SCORED | 1.1.16 | PATCH | L1 | MASTER | Ensure that the scheduler.conf file ownership is set to root:root"
  file:
    path: /etc/kubernetes/scheduler.conf
    state: file
    owner: root
    group: root
  when:
    - rule_1_1_16
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.16
    - master

- name: "SCORED | 1.1.17 | PATCH | L1 | MASTER | Ensure that the controller-manager.conf file permissions are set to 600 or more restrictive"
  file:
    path: /etc/kubernetes/controller-manager.conf
    state: file
    mode: 0600
  when:
    - rule_1_1_17
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.17
    - master

- name: "SCORED | 1.1.18 | PATCH | L1 | MASTER | Ensure that the controller-manager.conf file ownership is set to root:root"
  file:
    path: /etc/kubernetes/controller-manager.conf
    state: file
    owner: root
    group: root
  when:
    - rule_1_1_18
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.18
    - master

- name: "SCORED | 1.1.19 | PATCH | L1 | MASTER | Ensure that the Kubernetes PKI directory and file ownership is set to root:root"
  file:
    path: /etc/kubernetes/pki/
    state: directory
    owner: root
    group: root
  when:
    - rule_1_1_19
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.19
    - master

- name: "SCORED | 1.1.20 | PATCH | L1 | MASTER | Ensure that the Kubernetes PKI certificate file permissions are set to 600 or more restrictive"
  file:
    path: /etc/kubernetes/pki/
    state: directory
    mode: 0600
  when:
    - rule_1_1_20
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.20
    - master

- name: "SCORED | 1.1.21 | PATCH | L1 | MASTER | Ensure that the Kubernetes PKI certificate file permissions are set to 600 or more restrictive (1/2)"
  find:
    paths: /etc/kubernetes/pki
    patterns: '*.key'
    file_type: directory
  when:
    - rule_1_1_21
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.21
    - master
  register: result

- name: "SCORED | 1.1.21 | PATCH | L1 | MASTER | Ensure that the Kubernetes PKI certificate file permissions are set to 600 or more restrictive (2/2)"
  file:
    path: "{{ item.path }}"
    state: file
    mode: 0600
  loop: "{{ result.files }}"
  when:
    - rule_1_1_21
  tags:
    - level1
    - perms
    - patch
    - rule_1.1.21
    - master